### ISSUE TITLE
JIRA: more clear done issues in agile board planning view

### ISSUE THREAD

**Issue by yugecin** [yugecin/compactweb#7]
```CSS
div.ghx-issue-compact.ghx-done div.ghx-summary {
    text-decoration: line-through;
}
```
